name: ecotech
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.0
  url_launcher: ^6.0.20



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl: ^0.17.0 # Adicione esta linha
  carousel_slider: ^4.1.1 

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
    - assets/ecotech-removebg-preview.png
    - assets/imagem1.jpg
    - assets/imagem2.jpg
    - assets/imagem3.jpg
    - assets/mato.jpg
    - assets/fundo.jpg
    - assets/robertao.jpeg
    - assets/post0.jpeg
    - assets/post1.jpeg
    - assets/post2.jpeg
    - assets/post3.jpeg
    - assets/post4.jpeg
    - assets/post5.jpeg
    - assets/primeiro.png
    - assets/segundo.png
    - assets/fundo.jpg
    - assets/locais.jpg
    - assets/post6.jpeg
    - assets/post7.jpeg